services:
  - type: web
    name: dle-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000